# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
coveralls: true
os:
  - linux
  - osx
julia:
  - 1.0
  - 1
notifications:
  email: false
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install liblapack-dev libblas-dev; # For CSDP
    fi
jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.add("DynamicPolynomials");
                                    Pkg.add(PackageSpec(url="https://github.com/blegat/Documenter.jl", rev="latexout"));
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
    - stage: "Examples"
      julia: 1
      os: linux
      script:
        - julia --project=examples -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=examples --color=yes examples/run_examples.jl
